- contracts/MasterChef.sol
Hi MasterChef,
What do you think of this? Try saving some gas when making sushi.
Your Sushi Staff
> Optimize gas when depositing or withdrawing

- contracts/MasterChef.sol
> Fix typo in MasterChef

- README.md
- contracts/Migrator2.sol
- package.json
- scripts/prepublish.js
Migrator2 is a contract to support converting from Uniswap LP to Sushiswap LP tokens.
Also, I've updated package.json to publish as a npm package.
> Migrator2 contract and npm package config

- contracts/SushiMaker.sol
- contracts/mocks/RevertingERC20Mock.sol
- contracts/mocks/SushiMakerExploitMock.sol
- hardhat.config.js
- test/SushiMaker.test.js
- test/utilities/index.js
- yarn.lock
Increased test coverage for SushiMaker to 98%
> feat:  added tests for SushiMaker

- test/MasterChefV2.test.js
- test/utilities/time.js
100% Statements 82/82
77.78% Branches 14/18
100% Functions 14/14
100% Lines 80/80
> MasterChefV2: added tests

- test/MasterChefV2.test.js
- test/utilities/index.js
100% Statements 82/82
100% Branches 18/18
100% Functions 14/14
100% Lines 80/80
> MasterChefV2: added tests to achieve 100% branch coverage

- .github/workflows/sushiswap.yml
- .mythx.yml
This PR will make two contributions:
- Add a `.mythx.yml` configuration file into the repository to quickly submit contracts for security scans powered by [MythX](http://mythx.io/).
- Add an additional workflow step that submits contracts to the MythX API.
By default, the configuration file runs in async mode. This means that the CLI will not wait for the contracts' analysis to finish once they have been submitted to the API. Alternatively, in the YAML file, set `async: false` to wait for the analyses to finish. In conjunction with the `ci: true` setting, the CLI will return 1 if issues above low severity have been found and the CI run will fail.
For the analysis to work, an environment variable `MYTHX_API_KEY` containing the JWT secret obtained from the [MythX …
> MythX Integration

- .github/workflows/sushiswap.yml
- .mythx.yml
This PR will properly fetch the MythX API key env var from the repo secrets and fix an issue in the CI pipeline where contract dependencies were not properly pulled.
> Add Github secrets config and missing CI setup step

- hardhat.config.ts
- package.json
- tsconfig.json
- yarn.lock
This is the first step to achieve the migration of tests to typescript.
#54
> feat: setup typescript

- contracts/MasterChefV2.sol
- contracts/interfaces/IMasterChef.sol
- contracts/interfaces/IRewarder.sol
This PR makes minor formatting changes to conform syntax and aid auditability, as well as:
* index `rewarder` in `LogSetPool()` event to match format of `LogPoolAddition()` event.
* add `return` statement in `harvest()` function to remove warnings around low-level call; should also promote builds on top of this function.
> Formatting changes to MasterChefV2

- contracts/SushiBar.sol
Fixes spelling of unlocks.
Come build on Edgeware y'all!
> Fixes spelling

- .prettierrc.js
- package.json
- test/MasterChef.test.ts
- test/MasterChefV2.test.ts
- test/Migrator.test.ts
- test/SushiBar.test.ts
- test/SushiMaker.test.ts
- test/SushiToken.test.ts
- test/Timelock.test.ts
- test/utilities/index.ts
- test/utilities/time.ts
Second step toward test re-written in ts.
> migrate test to ts

- contracts/MasterChefV2.sol
- contracts/interfaces/IRewarder.sol
- contracts/mocks/RewarderBrokenMock.sol
- contracts/mocks/RewarderMock.sol
To allow for more complex rewarder implementations, changes in LP tokens staked are passed along
> Advanced Information on LP

- apps/furo/components/HistoryPopover.tsx
- apps/furo/components/StreamDetailsPopover.tsx
- apps/furo/components/stream/CreateMultipleForm/ImportZone.tsx
- apps/furo/components/vesting/CreateForm/CreateFormReviewModal.tsx
- apps/furo/components/vesting/CreateForm/GradedVestingDetailsSection.tsx
- apps/furo/components/vesting/CreateForm/schema.ts
- apps/furo/components/vesting/CreateMultipleForm/CreateMultipleForm.tsx
- apps/furo/components/vesting/CreateMultipleForm/ImportZone.tsx
- apps/furo/components/vesting/CreateMultipleForm/TableSectionRow.tsx
- apps/furo/components/vesting/SchedulePopover.tsx
fix(apps/furo): use timestamps instead of dates
> fix(apps/furo): add more input validation

- apps/furo/next-seo.config.mjs
- apps/furo/package.json
- apps/furo/pages/_app.tsx
- apps/furo/pages/dashboard.tsx
- apps/furo/pages/index.tsx
- apps/furo/pages/stream/[id].tsx
- apps/furo/pages/stream/create/index.tsx
- apps/furo/pages/stream/create/multiple.tsx
- apps/furo/pages/stream/create/single.tsx
- apps/furo/pages/user/[address]/index.tsx
- apps/furo/pages/vesting/[id].tsx
- apps/furo/pages/vesting/create/index.tsx
- apps/furo/pages/vesting/create/multiple.tsx
- apps/furo/pages/vesting/create/single.tsx
- apps/partner/next-seo.config.mjs
- apps/partner/package.json
- apps/partner/pages/_app.tsx
- pnpm-lock.yaml
not sure if we shouldn't go for things like 
`Furo | Sushi`
`Dashboard | Sushi`
`Stream #123 | Sushi`
or 
`Furo`
`Dashboard | Furo`
`Stream #123 | Furo`
what do you think @chillichelli?
> feat(apps/furo): add basic seo

- apps/pool/.graphclientrc.yml
- apps/pool/components/PoolsSection/Tables/PoolsTable/PoolsTable.tsx
- apps/pool/lib/api.ts
- apps/pool/pages/index.tsx
- apps/pool/query.graphql
- apps/pool/resolvers.ts
@chillichelli only thing you need to do is add arrows, you can plug into the pagination state in PoolsTable.tsx
> feat(apps/pool): backend for pagination

- apps/furo/.graphclientrc.yml
- apps/furo/config.ts
- apps/furo/lib/Furo.ts
- apps/furo/lib/Stream.ts
- apps/furo/lib/Vesting.ts
- apps/furo/pages/index.tsx
- apps/furo/pages/stream/[id].tsx
- apps/furo/query.graphql
waiting for new subgraph to be deployed still
edit: deployed now
edit: still something else to fix, don't merge yet
> fix(apps/furo): streamed balance not calculated correctly

- packages/wagmi/hooks/usePrices.ts
> fix(apps/swap): opendao / sos pricing issue

- apps/invest/components/RemoveSection/RemoveSectionLegacy.tsx
- apps/invest/components/RemoveSection/RemoveSectionTrident.tsx
- apps/invest/components/RemoveSection/RemoveSectionUnstake.tsx
- apps/invest/components/RemoveSection/RemoveSectionUnstakeWidget.tsx
- apps/invest/components/RemoveSection/RemoveSectionWidget.tsx
- packages/ui/input/Numeric.tsx
- packages/ui/input/Percent.tsx
- packages/ui/input/index.ts
- packages/ui/input/utils.ts
fix(apps/pool): remove unnecessary useMemos
fix(apps/pool): show no staked tokens found overlay if no staked balance
> fix(apps/pool): #308

- apps/analytics/components/Table/PairVolume1wCell.tsx
- apps/analytics/components/Table/constants.tsx
- apps/analytics/components/TokenSection/TokenPairs.tsx
- apps/earn/components/PoolSection/PoolChart.tsx
- apps/earn/components/PoolSection/PoolStats.tsx
- packages/graph-client/.graphclientrc.yml
- packages/graph-client/fetchers/block.ts
- packages/graph-client/fetchers/index.ts
- packages/graph-client/queries/sushiswap.graphql
- packages/graph-client/resolvers/sushiswap.ts
> fix(apps/earn): rolling volume, rename vol7d to vol1w

- packages/config/wagmi/src/index.ts
> Boba Avex to Boba Avax

- pnpm-lock.yaml
- scripts/farms/package.json
- scripts/farms/query.graphql
- scripts/farms/src/lib/chefs/minichef/fetchers.ts
- scripts/farms/src/lib/common/pairs.ts
- scripts/farms/src/lib/common/tokens.ts
- scripts/farms/src/lib/wagmi.ts
Reverts sushiswap/sushiswap#455
> Revert "fix(scripts/farms): fixes all around"

- apps/analytics/components/TokenSection/TokenPairs.tsx
migrate /pool route to /earn route
> fix: /pool route 404

- packages/graph-client/lib/wagmi.ts
Waiting for wagmi to merge fix
> fix(packages/gc): revert to readContracts

- apis/tokens/lib/api.ts
- packages/database/prisma/schema.prisma
- pnpm-lock.yaml
https://tokens-git-feature-add-fot-common-fields-to-db.sushi.com/v0/42170/0xefaeee334f0fd1712f9a8cc375f427d9cdd40d73
> feat(packages/database): add token.feeOnTransfer and token.isCommon

- apis/tokens/api/v0/[chainId]/[address].ts
- apis/tokens/api/v0/[chainId]/common.ts
- apis/tokens/api/v0/[chainId]/popular.ts
- apis/tokens/lib/api.ts
- apis/tokens/package.json
- pnpm-lock.yaml
Examples:
https://tokens-git-feature-tokens-api-common-list.sushi.com/v0/1/0x68ca006db91312cd60a2238ce775be5f9f738bba
https://tokens-git-feature-tokens-api-common-list.sushi.com/v0/1/common
https://tokens-git-feature-tokens-api-common-list.sushi.com/v0/1/popular
> Token/[chainId]/address wagmi fallback, Common and Popular endpoint 

- packages/wagmi/future/components/ConnectButton.tsx
Reverts sushiswap/sushiswap#717
> Revert "fix(apps/swap): connect wallet button going on a diet"

- packages/wagmi/future/hooks/approvals/hooks/useTokenApproval.ts
fix(packages/wagmi): didnt check equal amount
> fix(packages/wagmi): bug on native

- apps/_root/lib/swap/queryParamsSchema.ts
- apps/_root/ui/swap/TokenProvider.tsx
- apps/_root/ui/swap/trade/TradeProvider.tsx
- packages/v3-sdk/src/constants.ts
Reverts sushiswap/sushiswap#877
> Revert "fix(apps/swap): default quote currency"

- apps/web/src/app/(non-evm)/aptos/(common)/components/AddSection/AddSectionWidget.tsx
- apps/web/src/app/(non-evm)/aptos/(common)/components/RemoveSection/RemoveSectionWidget.tsx
- apps/web/src/app/(non-evm)/tron/_common/ui/Pools/Manage/AddSection.tsx
- apps/web/src/app/(non-evm)/tron/_common/ui/Pools/Manage/RemoveSection.tsx
- apps/web/src/ui/pool/AddSectionLegacy.tsx
- apps/web/src/ui/pool/AddSectionReviewModalConcentrated.tsx
- apps/web/src/ui/pool/AddSectionReviewModalLegacy.tsx
- apps/web/src/ui/pool/AddSectionWidget.tsx
- apps/web/src/ui/pool/ConcentratedLiquidityRemoveWidget.tsx
- apps/web/src/ui/pool/MigrateTab.tsx
- apps/web/src/ui/pool/RemoveSectionLegacy.tsx
- apps/web/src/ui/pool/RemoveSectionWidget.tsx
- apps/web/src/ui/pool/Steer/SteerLiquidityManagement/Add/SteerPositionAdd.tsx
- apps/web/src/ui/pool/Steer/SteerLiquidityManagement/Remove/SteerPositionRemove.tsx
- apps/web/src/ui/pool/V3PositionView.tsx
- apps/web/src/ui/swap/simple/simple-swap-bridge-banner.tsx
consistent use of same settings icon across the app and primary buttons
replace some v1 heroicons
> housekeeping

- apps/web/src/app/(networks)/(evm)/api/config/version/route.ts
- apps/web/src/app/(networks)/layout.tsx
- apps/web/src/app/_common/app-version/new-app-version-dialog.tsx
- apps/web/src/app/_common/app-version/use-app-version.ts
> feat: new app version dialog

- apps/web/src/lib/wagmi/components/user-portfolio/PortfolioDefaultView.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/index.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/portfolio-assets/claimable-assets.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/portfolio-assets/position-assets.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/portfolio-assets/wallet-assets.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/portfolio-orders/active-orders.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/portfolio-orders/completed-order-item.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/portfolio-orders/completed-orders.tsx
- apps/web/src/lib/wagmi/components/user-portfolio/portfolio-orders/portfolio-orders.tsx
- config/tailwindcss/index.js
Allows a user to quickly view current or past Limit and DCA orders.
> Feature/dex 38: Orders tab in account drawer

- apps/web/src/ui/pool/AddSectionReviewModalConcentrated.tsx
> fix: format v3 deposit values

- apps/web/src/app/(networks)/(evm)/stake/_ui/BarSection.tsx
Reverts sushi-labs/sushiswap#1982
> Revert "fix(apps/web): raise slippage for xsushi un/staking"
